lib/rumbl/web/router.ex
defmodule Rumbl.Web.Router do
  use Rumbl.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Rumbl.Auth, context: Rumbl.ContentCreation
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Rumbl.Web do
    pipe_through :browser # Use the default browser stack

    get "/",               PageController, :index
    resources "/users",    UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/watch/:id",      WatchController, :show
  end

  scope "/manage", Rumbl.Web do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Rumbl.Web do
  #   pipe_through :api
  # end
end

lib/rumbl/web/controllers/page_controller.ex
defmodule Rumbl.Web.PageController do
  use Rumbl.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/rumbl/web/controllers/session_controller.ex
defmodule Rumbl.Web.SessionController do
  use Rumbl.Web, :controller

  alias Rumbl.Auth
  alias Rumbl.ContentCreation

  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => %{"username" => user, "password" => pass}}) do
    case Auth.login_by_username_and_password(conn, user, pass,
                                                   context: ContentCreation) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: page_path(conn, :index))
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> Auth.logout
    |> redirect(to: page_path(conn, :index))
  end
end

lib/rumbl/web/controllers/user_controller.ex
defmodule Rumbl.Web.UserController do
  use Rumbl.Web, :controller

  plug :authenticate_user when action in [:index, :show]

  alias Rumbl.ContentCreation
  alias Rumbl.ContentCreation.User
  alias Rumbl.Auth

  def index(conn, _params) do
    users = ContentCreation.list_users()
    render(conn, "index.html", users: users)
  end

  def show(conn, %{"id" => id}) do
    user = ContentCreation.get_user(id)
    render(conn, "show.html", user: user)
  end

  def new(conn, _params) do
    changeset = ContentCreation.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case ContentCreation.create_user(user_params) do
      {:ok, user} ->
        conn
        |> Auth.login(user)
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/rumbl/web/controllers/video_controller.ex
defmodule Rumbl.Web.VideoController do
  use Rumbl.Web, :controller
  alias Rumbl.ContentCreation

  plug :load_categories when action in [:new, :create, :edit, :update]

  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
         [conn, conn.params, conn.assigns.current_user])
  end

  def index(conn, _params, user) do
    videos = ContentCreation.list_user_videos(user)
    render(conn, "index.html", videos: videos)
  end

  def new(conn, _params, user) do
    changeset = ContentCreation.change_user_video(user)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" => video_params}, user) do
    case ContentCreation.create_user_video(user, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video created successfully.")
        |> redirect(to: video_path(conn, :show, video))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, user) do
    video = ContentCreation.get_user_video!(user, id)
    render(conn, "show.html", video: video)
  end

  def edit(conn, %{"id" => id}, user) do
    video = ContentCreation.get_user_video!(user, id)
    changeset = ContentCreation.change_video(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params}, user) do
    video = ContentCreation.get_user_video!(user, id)

    case ContentCreation.update_video(video, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: video_path(conn, :show, video))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, user) do
    video = ContentCreation.get_user_video!(user, id)
    {:ok, _video} = ContentCreation.delete_video(video)

    conn
    |> put_flash(:info, "Video deleted successfully.")
    |> redirect(to: video_path(conn, :index))
  end

  #
  ## Plugs

  defp load_categories(conn, _) do
    categories = ContentCreation.load_categories_names_and_ids_alphabetically
    assign(conn, :categories, categories)
  end
end

lib/rumbl/web/controllers/watch_controller.ex
defmodule Rumbl.Web.WatchController do
  use Rumbl.Web, :controller 
  alias Rumbl.ContentCreation

  def show(conn, %{"id" => id}) do
    video = ContentCreation.get_video!(id) 
    render conn, "show.html", video: video
  end
end

lib/rumbl/web/views/annotation_view.ex
defmodule Rumbl.Web.AnnotationView do
  use Rumbl.Web, :view
  alias Rumbl.Web.UserView

  def render("annotation.json", %{annotation: an}) do
    %{
      id: an.id,
      body: an.body,
      at: an.at,
      user: render_one(an.user, UserView, "user.json")
    }
  end
end

lib/rumbl/web/views/error_view.ex
defmodule Rumbl.Web.ErrorView do
  use Rumbl.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/rumbl/web/views/layout_view.ex
defmodule Rumbl.Web.LayoutView do
  use Rumbl.Web, :view
end

lib/rumbl/web/views/page_view.ex
defmodule Rumbl.Web.PageView do
  use Rumbl.Web, :view
end

lib/rumbl/web/views/session_view.ex
defmodule Rumbl.Web.SessionView do
  use Rumbl.Web, :view
end

lib/rumbl/web/views/user_view.ex
defmodule Rumbl.Web.UserView do
  use Rumbl.Web, :view

  alias Rumbl.ContentCreation.User

  def first_name(%User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end

  def render("user.json", %{user: user}) do
    %{id: user.id, username: user.username}
  end
end

lib/rumbl/web/views/video_view.ex
defmodule Rumbl.Web.VideoView do
  use Rumbl.Web, :view
end

lib/rumbl/web/views/watch_view.ex
defmodule Rumbl.Web.WatchView do
  use Rumbl.Web, :view

  def player_id(video) do
    ~r{^.*(?:youtu\.be/|\w+/|v=)(?<id>[^#&?]*)} 
    |> Regex.named_captures(video.url)
    |> get_in(["id"])
  end
end

lib/rumbl/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Rumbl!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="breadcrumb text-right">
            <%= if @current_user do %>
              <li><%= @current_user.username %></li>
              <li><%= link "My Videos", to: video_path(@conn, :index) %></li>
              <li>
                <%= link "Log out", to: session_path(@conn, :delete, @current_user),
                                       method: "delete" %>
              </li>
            <% else %>
              <li><%= link "Register", to: user_path(@conn, :new) %></li>
              <li><%= link "Log in",   to: session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/rumbl/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Rumbl.io!</h2>
  <p class="lead">Rumble out loud.</p>
</div>

lib/rumbl/web/templates/session/new.html.eex
<h1>Login</h1>
<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
   </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= submit "Log in", class: "btn btn-primary" %>
<% end %>

lib/rumbl/web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table class="table">
  <%= for user <- @users do %>
    <tr>
      <td><%= render("user.html", user: user) %></td>
      <td><%= link("View", to: user_path(@conn, :show, user.id)) %></td>
    </tr>
  <% end %>
</table>

lib/rumbl/web/templates/user/new.html.eex
<h1>New User</h1>
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>Ooops, something went wrong! Please check errors below.</p>
  </div>
<% end %>

<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
    <%= error_tag f, :name %>
  </div>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
    <%= error_tag f, :username %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Create User", class: "btn btn-primary" %>
<% end %>

lib/rumbl/web/templates/user/show.html.eex
<h1>Showing User</h1>
<%= render("user.html", user: @current_user) %>

lib/rumbl/web/templates/user/user.html.eex
<b><%= first_name(@user) %></b> (<%= @user.id %>)</b>

lib/rumbl/web/templates/video/edit.html.eex
<h2>Edit Video</h2>

<%= render "form.html", changeset: @changeset, categories: @categories,
                        action: video_path(@conn, :update, @video) %>

<span><%= link "Back", to: video_path(@conn, :index) %></span>

lib/rumbl/web/templates/video/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :url, class: "control-label" %>
    <%= text_input f, :url, class: "form-control" %>
    <%= error_tag f, :url %>
  </div>

  <div class="form-group">
    <%= label f, :category_id, "Category", class: "control-label" %>
    <%= select f, :category_id, @categories, class: "form-control", 
                                prompt: "Choose a category" %>
  </div>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/rumbl/web/templates/video/index.html.eex
<h2>Listing Videos</h2>

<table class="table">
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for video <- @videos do %>
    <tr>
      <td><%= video.url %></td>
      <td><%= video.title %></td>
      <td><%= video.description %></td>

      <td class="text-right">
        <span><%= link "Watch",   to: watch_path(@conn, :show, video), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit",    to: video_path(@conn, :edit, video), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete",  to: video_path(@conn, :delete, video), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Video", to: video_path(@conn, :new) %></span>

lib/rumbl/web/templates/video/new.html.eex
<h2>New Video</h2>

<%= render "form.html", changeset: @changeset, categories: @categories,
                        action: video_path(@conn, :create) %>

<span><%= link "Back", to: video_path(@conn, :index) %></span>

lib/rumbl/web/templates/video/show.html.eex
<h2>Show Video</h2>

<ul>

  <li>
    <strong>Url:</strong>
    <%= @video.url %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @video.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @video.description %>
  </li>

</ul>

<span><%= link "Edit", to: video_path(@conn, :edit, @video) %></span>
<span><%= link "Back", to: video_path(@conn, :index) %></span>

lib/rumbl/web/templates/watch/show.html.eex
<h2><%= @video.title %></h2> 
<div class="row">
  <div class="col-sm-7">
    <%= content_tag :div, id: "video", data: [id: @video.id, player_id: player_id(@video)] do %>
    
    <% end %>
  </div>
  <div class="col-sm-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Annotations</h3>
      </div>
      <div id="msg-container" class="panel-body annotations">

      </div>
      <div class="panel-footer">
        <textarea id="msg-input" rows="3" class="form-control" placeholder="Comment..."></textarea>
        <button id="msg-submit" class="btn btn-primary form-control" type="submit">
          Post
        </button>
      </div>
    </div>
  </div>
</div>